markdown: kramdown
permalink: /:title/
url: http://wanguolin.github.io
name: Guolin.Wan_Tech_Reading
author: Guolin.Wan
qq: 845892972
email: wanguolin@gmail.com
duoshuo: wanguolin
beian: 就不备案 
cnzz: 1000233772
github: wanguolin
pygments: true
safe: true
paginate: 20
about: "这是我在github搭建的一个读书笔记类型的博客，他采用了yihui同学的框架。"

